openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: alguna descripción
  termsOfService: http://swagger.io/terms/
  contact:
    email: jorgechilconp@bcp.com.pe
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: buscar empleados
  url: http://swagger.io
servers:
  - url: https://petstore3.swagger.io/api/v3

paths:
  /empleados/{userId}:
    get:
      tags:
        - users
      summary: Buscar usuario por id
      description: retornar usuarios
      parameters:
        - name: userId
          in: path
          description: id del usuario
          required: true
          schema:
            type: string
      responses:
        '200':
          description: operación satisfactoria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'

        '400':
          description: id invalido.
        '404':
          description: Usuario no encontrado.

components:
  schemas:
    UserResponse:
      required:
        - id
        - name
        - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        edad:
          type: integer
          example: 25
        name:
          type: string
          example: 'Juan Perez'
        category:
          $ref: '#/components/schemas/Categoria'
        empleados:
          type: array
          items:
            $ref: '#/components/schemas/Empleado'
        status:
          type: string
          description: estado de la persona
          enum:
            - available
            - pending
            - sold
      xml:
        name: user
    Categoria:
      properties:
        id:
          type: string
          example: "1234"
        name:
          type: string
          example: "Gerencia General"
        typeId:
          type: integer
          example: 987
    Empleado:
      type: object
      required:
        - id
        - nombre
        - telefono
      properties:
        id:
          type: integer
          format: int64
          example: 1
        nombre:
          type: string
          example: "Ana Gómez"
        telefono:
          type: string
          example: "987654321"
        edad:
          type: integer
          example: 24
