version: "3.9"
services:
  spring-api-image:
    image: api-ms-customer
    container_name: api-ms-customer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - spring-network

networks:
  spring-network:
#volumes:
#  mysql-volume: